
const assert = require('yeoman-assert');
const helpers = require('yeoman-test');
const path = require('path');
const NodeConfig = require('../package.json');

describe('yo <%= generator %>:service', () => {

    let tempDir = '';

    beforeEach(() => {
        return helpers
            .run(path.join(__dirname, '../generators/service'))
            .inTmpDir(function (dir) {
                tempDir = dir;
                // fs.copySync(path.join(__dirname, '../templates/common'), dir)
            })
            .withOptions({ init: true })
            .withArguments(['unit-test', 'io.test'])
            .then(() =>
                {
                    // assert.file(['.yo-rc.json']);
                });
    });

    it('yo config', () => {
        assert.file(['.yo-rc.json']);

        // assert.jsonFileContent('.yo-rc.json', { 'generator-zic': { version: NodeConfig.version, description: 'This project was generated by the project \"generator-zic\"' } });
    });

    // it('git', () => {
    //     assert.file(['.gitignore']);
    // });

    // it('docker', () => {
    //     assert.file(['Dockerfile']);
    // });

    // it('gradle', () => {
    //     assert.file(['build.gradle', 'gradlew', 'gradlew.bat', 'gradle/wrapper/gradle-wrapper.jar', 'gradle/wrapper/gradle-wrapper.properties']);
    // });

    it('editors', () => {
        assert.file(['.vscode/settings.json']);
    });

    // it('documentation', () => {
    //     assert.file(['README.md']);
    // });

    // it('java', () => {

    //     const javaFiles = [
    //         'src/main/java/io/test/service/unit/test/UnitTestService.java',
    //         'src/main/java/io/test/service/unit/test/controllers/ExampleController.java',
    //         'src/main/java/io/test/service/unit/test/models/GreetingModel.java',
    //         'src/test/java/io/test/service/unit/test/UnitTestServiceTests.java',
    //         'src/test/java/io/test/service/unit/test/controllers/ExampleControllerTests.java',
    //         'src/integTest/java/io/test/service/unit/test/BaseIntegrationTest.java',
    //         'src/integTest/java/io/test/service/unit/test/IntegrationTest.java',
    //         'src/integTest/java/io/test/service/unit/test/IntegrationTestCategory.java',
    //         'src/integTest/java/io/test/service/unit/test/controllers/ExampleControllerIntegrationTests.java'];

    //     assert.file(javaFiles);
        
    //     javaFiles.forEach(javaFile => {
    //         assert.fileContent(javaFile, /^package io.test.service.unit.test/);
    //     });
    // });

    // it('java configuration', () => {
    //     assert.file([
    //         'src/main/resources/application-integration.yml',
    //         'src/main/resources/application-local.yml',
    //         'src/main/resources/application.yml']);
    // });
});
